import 'dart:async';
import 'dart:convert';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import 'package:web_socket_channel/web_socket_channel.dart';
import 'remote_service.dart';

/// WebRTC Service for Remote Preview v0.1
/// Handles: PeerConnection, signaling WebSocket, SDP/ICE
class WebRTCService {
  RTCPeerConnection? _peerConnection;
  WebSocketChannel? _wsChannel;
  MediaStream? _localStream;
  MediaStream? _remoteStream;
  
  final String sessionId;
  final bool isHost;
  
  // ICE candidate counters for debugging
  int _iceCandidateGeneratedCount = 0; // Total generated by ICE agent
  int _iceCandidateSentCount = 0;       // Actually sent via WS
  int _iceCandidateReceivedCount = 0;   // Received from peer
  
  // Queue for ICE candidates generated before WS is connected
  final List<RTCIceCandidate> _pendingIceCandidates = [];
  
  // Callbacks
  Function(MediaStream)? onRemoteStream;
  Function(RTCPeerConnectionState)? onConnectionState;
  Function(String)? onError;
  
  // 2-step host_ready callbacks
  Function(String requestId)? onEnableScreenCapture; // Host receives: show MediaProjection
  Function()? onWaitHostReady; // Controller receives: show waiting UI
  Function(String sessionId, String controllerToken)? onHostReady; // Controller receives: auto-continue SDP
  
  WebRTCService({
    required this.sessionId,
    required this.isHost,
  });

  /// Initialize WebRTC with TURN credentials
  Future<bool> initialize() async {
    try {
      // Get TURN credentials
      final turnCreds = await RemoteService.getTurnCredentials(sessionId);
      if (turnCreds == null) {
        onError?.call('Failed to get TURN credentials');
        return false;
      }

      // ICE servers configuration - IMPORTANT: 'all' allows STUN fallback if TURN fails
      final iceServers = [
        {
          'urls': turnCreds.urls,
          'username': turnCreds.username,
          'credential': turnCreds.credential,
        },
        // Fallback STUN servers
        {'urls': 'stun:stun.l.google.com:19302'},
        {'urls': 'stun:stun1.l.google.com:19302'},
        {'urls': 'stun:stun2.l.google.com:19302'},
      ];
      
      final config = {
        'iceServers': iceServers,
        // Changed from 'relay' to 'all' - 'relay' with unreachable TURN = 0 candidates!
        'iceTransportPolicy': 'all',
      };
      
      // Log ICE configuration for debugging
      final role = isHost ? 'HOST' : 'CONTROLLER';
      print('[WebRTC] [$role] ICE CONFIG:');
      print('[WebRTC] [$role]   iceTransportPolicy: ${config['iceTransportPolicy']}');
      print('[WebRTC] [$role]   iceServers count: ${iceServers.length}');
      for (int i = 0; i < iceServers.length; i++) {
        final server = iceServers[i];
        final urls = server['urls'];
        final hasAuth = server.containsKey('username');
        print('[WebRTC] [$role]   [$i] urls=$urls, hasAuth=$hasAuth');
      }

      // Create peer connection
      print('[WebRTC] [$role] Creating peer connection...');
      _peerConnection = await createPeerConnection(config);
      print('[WebRTC] [$role] Peer connection created');
      
      // Set up event handlers
      _peerConnection!.onIceCandidate = _onIceCandidate;
      _peerConnection!.onTrack = _onTrack;
      _peerConnection!.onConnectionState = (state) {
        print('[WebRTC] Connection state: $state');
        onConnectionState?.call(state);
      };
      
      // ICE connection state handler - send via WS (NOT HTTP)
      _peerConnection!.onIceConnectionState = (RTCIceConnectionState state) {
        print('[WebRTC] ICE connection state: $state');
        _reportIceStateViaWS(state.toString());
      };
      
      // ICE gathering state handler - critical for debugging
      _peerConnection!.onIceGatheringState = (RTCIceGatheringState state) {
        final role = isHost ? 'HOST' : 'CONTROLLER';
        print('[WebRTC] [$role] ICE GATHERING STATE: $state');
        if (state == RTCIceGatheringState.RTCIceGatheringStateComplete) {
          print('[WebRTC] [$role] ICE gathering COMPLETE. Generated=$_iceCandidateGeneratedCount, Sent=$_iceCandidateSentCount, Pending=${_pendingIceCandidates.length}');
        }
      };

      print('[WebRTC] Initialized with TURN: ${turnCreds.urls}');
      return true;
    } catch (e) {
      print('[WebRTC] Initialize error: $e');
      onError?.call(e.toString());
      return false;
    }
  }

  /// Connect to signaling WebSocket
  /// wsToken can be null for host pre-token mode (new 2-step contract)
  Future<bool> connectSignaling({String? wsToken}) async {
    try {
      // Log token presence BEFORE building URL
      print('[WebRTC] connectSignaling: token=${wsToken != null && wsToken.isNotEmpty ? 'present (${wsToken.length} chars)' : 'EMPTY/NULL'}');
      
      final wsUrl = RemoteService.signalingUrl(sessionId: sessionId, wsToken: wsToken ?? '');
      
      // Parse and log URL details for debugging
      final uri = Uri.parse(wsUrl);
      print('[WebRTC] WS URL scheme: ${uri.scheme}');
      print('[WebRTC] WS URL host: ${uri.host}:${uri.port}');
      print('[WebRTC] WS URL path: ${uri.path}');
      print('[WebRTC] WS URL (masked): ${uri.scheme}://${uri.host}:${uri.port}${uri.path}?token=${wsToken != null && wsToken.isNotEmpty ? '${wsToken.substring(0, 10)}...' : 'EMPTY'}');
      
      // Verify scheme is ws:// or wss://
      if (uri.scheme != 'ws' && uri.scheme != 'wss') {
        print('[WebRTC] ERROR: Invalid WS scheme "${uri.scheme}" - must be ws or wss!');
        onError?.call('Invalid WebSocket scheme: ${uri.scheme}');
        return false;
      }
      
      print('[WebRTC] Attempting WebSocket connect...');
      _wsChannel = WebSocketChannel.connect(uri);
      
      _wsChannel!.stream.listen(
        (message) => _handleSignalingMessage(message),
        onError: (e) {
          print('[WebRTC] WS error: $e');
          onError?.call('Signaling error: $e');
        },
        onDone: () {
          print('[WebRTC] WS closed');
        },
      );

      print('[WebRTC] WebSocket connected successfully');
      
      // Flush any pending ICE candidates that were queued before WS was ready
      _flushPendingIceCandidates();
      
      return true;
    } catch (e) {
      print('[WebRTC] Connect signaling error: $e');
      onError?.call(e.toString());
      return false;
    }
  }

  /// Start as viewer (receive remote stream)
  Future<void> startViewer() async {
    print('[WebRTC] [CONTROLLER] startViewer() called');
    
    if (_peerConnection == null) {
      print('[WebRTC] [CONTROLLER] ERROR: _peerConnection is NULL in startViewer!');
      return;
    }

    // Add transceiver for receiving video
    print('[WebRTC] [CONTROLLER] Adding video transceiver...');
    await _peerConnection!.addTransceiver(
      kind: RTCRtpMediaType.RTCRtpMediaTypeVideo,
      init: RTCRtpTransceiverInit(direction: TransceiverDirection.RecvOnly),
    );
    print('[WebRTC] [CONTROLLER] Adding audio transceiver...');
    await _peerConnection!.addTransceiver(
      kind: RTCRtpMediaType.RTCRtpMediaTypeAudio,
      init: RTCRtpTransceiverInit(direction: TransceiverDirection.RecvOnly),
    );

    // Create offer - this triggers ICE gathering
    print('[WebRTC] [CONTROLLER] Creating SDP offer...');
    final offer = await _peerConnection!.createOffer();
    print('[WebRTC] [CONTROLLER] SDP offer created, length=${offer.sdp?.length ?? 0}');
    
    // Force VP8 codec for LDPlayer/Emulator compatibility
    String sdp = offer.sdp ?? '';
    sdp = _preferCodec(sdp, 'VP8');
    final newOffer = RTCSessionDescription(sdp, offer.type);
    
    // setLocalDescription triggers ICE candidate generation
    print('[WebRTC] [CONTROLLER] Setting local description (triggers ICE gathering)...');
    await _peerConnection!.setLocalDescription(newOffer);
    print('[WebRTC] [CONTROLLER] Local description set - ICE gathering should start now');
    
    // Send offer via signaling
    print('[WebRTC] [CONTROLLER] Sending SDP offer via WS...');
    _sendSignaling({
      'type': 'sdp_offer',
      'payload': {'sdp': newOffer.sdp},
    });

    print('[WebRTC] [CONTROLLER] startViewer() complete - waiting for ICE candidates + answer');
  }

  /// Start as host (send screen capture)
  Future<void> startHost(MediaStream screenStream) async {
    print('[WebRTC] [HOST] startHost() called');
    
    if (_peerConnection == null) {
      print('[WebRTC] [HOST] ERROR: _peerConnection is NULL in startHost!');
      return;
    }

    _localStream = screenStream;
    
    // Add screen capture tracks
    print('[WebRTC] [HOST] Adding ${screenStream.getTracks().length} tracks to peer connection...');
    for (final track in screenStream.getTracks()) {
      await _peerConnection!.addTrack(track, screenStream);
      print('[WebRTC] [HOST] Added track: ${track.kind}');
    }

    print('[WebRTC] [HOST] startHost() complete - waiting for SDP offer from controller');
  }

  /// Handle incoming signaling message
  void _handleSignalingMessage(dynamic message) async {
    try {
      print('[WebRTC] <<< RAW WS MESSAGE: $message');
      final data = json.decode(message);
      final type = data['type'];
      print('[WebRTC] <<< Parsed type=$type, full data=$data');
      final payload = (data['payload'] is Map<String, dynamic>)
          ? (data['payload'] as Map<String, dynamic>)
          : <String, dynamic>{};

      switch (type) {
        case 'sdp_offer':
          await _handleOffer(payload['sdp']?.toString() ?? '');
          break;
        case 'sdp_answer':
          await _handleAnswer(payload['sdp']?.toString() ?? '');
          break;
        case 'ice_candidate':
          await _handleIceCandidate(payload);
          break;
        case 'control_ready':
          print('[WebRTC] Control ready');
          break;
        // 2-step host_ready flow
        case 'enable_screen_capture':
          // Host receives: show MediaProjection prompt
          // Try multiple field names for request_id
          final requestId = payload['request_id']?.toString() ?? 
                           data['request_id']?.toString() ?? 
                           '';
          print('[WebRTC] >>> HOST: enable_screen_capture, request_id=$requestId, payload=$payload');
          onEnableScreenCapture?.call(requestId);
          break;
        case 'wait_host_ready':
          // Controller receives: show waiting UI, DO NOT SDP yet
          print('[WebRTC] Controller: wait_host_ready');
          onWaitHostReady?.call();
          break;
        case 'host_ready':
          // Controller receives: auto-continue SDP with session_id + controller_token
          final sid = payload['session_id']?.toString() ?? '';
          final ctoken = payload['controller_token']?.toString() ?? '';
          print('[WebRTC] Controller: host_ready, session_id=$sid');
          onHostReady?.call(sid, ctoken);
          break;
        case 'remote_cancelled':
        case 'remote_rejected':
          print('[WebRTC] Remote session cancelled/rejected');
          // Signal close
          onConnectionState?.call(RTCPeerConnectionState.RTCPeerConnectionStateClosed);
          break;
        case 'error':
          onError?.call(payload['message']?.toString() ?? 'Unknown error');
          break;
      }
    } catch (e) {
      print('[WebRTC] Handle message error: $e');
    }
  }

  /// Handle SDP offer (host receives from viewer)
  Future<void> _handleOffer(String sdp) async {
    print('[WebRTC] [HOST] _handleOffer() called, sdp length=${sdp.length}');
    
    if (_peerConnection == null) {
      print('[WebRTC] [HOST] ERROR: _peerConnection is NULL in _handleOffer!');
      return;
    }
    if (sdp.isEmpty) {
      print('[WebRTC] [HOST] ERROR: Received empty SDP offer!');
      onError?.call('Received empty SDP offer');
      return;
    }

    print('[WebRTC] [HOST] Setting remote description (offer)...');
    await _peerConnection!.setRemoteDescription(
      RTCSessionDescription(sdp, 'offer'),
    );
    print('[WebRTC] [HOST] Remote description set');

    print('[WebRTC] [HOST] Creating SDP answer...');
    final answer = await _peerConnection!.createAnswer();
    print('[WebRTC] [HOST] SDP answer created, length=${answer.sdp?.length ?? 0}');
    
    // Force VP8 codec in answer as well
    String sdp = answer.sdp ?? '';
    sdp = _preferCodec(sdp, 'VP8');
    final newAnswer = RTCSessionDescription(sdp, answer.type);
    
    print('[WebRTC] [HOST] Setting local description (triggers ICE gathering)...');
    await _peerConnection!.setLocalDescription(newAnswer);
    print('[WebRTC] [HOST] Local description set - ICE gathering should start now');

    print('[WebRTC] [HOST] Sending SDP answer via WS...');
    _sendSignaling({
      'type': 'sdp_answer',
      'payload': {'sdp': newAnswer.sdp},
    });

    print('[WebRTC] [HOST] _handleOffer() complete - waiting for ICE candidates');
  }

  /// Handle SDP answer (viewer receives from host)
  Future<void> _handleAnswer(String sdp) async {
    if (_peerConnection == null) return;
    if (sdp.isEmpty) {
      onError?.call('Received empty SDP answer');
      return;
    }

    await _peerConnection!.setRemoteDescription(
      RTCSessionDescription(sdp, 'answer'),
    );

    print('[WebRTC] Answer received');
  }

  /// Handle ICE candidate
  Future<void> _handleIceCandidate(Map<String, dynamic> data) async {
    if (_peerConnection == null) return;
    
    // Increment received counter
    _iceCandidateReceivedCount++;
    final role = isHost ? 'HOST' : 'CONTROLLER';
    print('[WebRTC] [$role] ICE candidate RECEIVED #$_iceCandidateReceivedCount');
    print('[WebRTC] [$role] ICE counts: sent=$_iceCandidateSentCount, received=$_iceCandidateReceivedCount');

    final candidate = RTCIceCandidate(
      data['candidate']?.toString(),
      data['sdpMid']?.toString(),
      data['sdpMLineIndex'] is int ? data['sdpMLineIndex'] as int : null,
    );
    await _peerConnection!.addCandidate(candidate);
  }

  /// ICE candidate event - called when ICE agent generates a candidate
  void _onIceCandidate(RTCIceCandidate candidate) {
    // Increment generated counter (total from ICE agent)
    _iceCandidateGeneratedCount++;
    
    final role = isHost ? 'HOST' : 'CONTROLLER';
    final candidateStr = candidate.candidate ?? '';
    
    // Determine candidate type
    String candidateType = 'unknown';
    if (candidateStr.contains('relay')) candidateType = 'relay (TURN)';
    else if (candidateStr.contains('srflx')) candidateType = 'srflx (STUN)';
    else if (candidateStr.contains('host')) candidateType = 'host (local)';
    
    print('[WebRTC] [$role] ICE CANDIDATE GENERATED #$_iceCandidateGeneratedCount: type=$candidateType');
    
    // Check if WS is connected
    if (_wsChannel == null) {
      print('[WebRTC] [$role] WARNING: WS not connected! Queuing candidate (queue size: ${_pendingIceCandidates.length + 1})');
      _pendingIceCandidates.add(candidate);
      return;
    }
    
    // Send via WS
    _iceCandidateSentCount++;
    print('[WebRTC] [$role] ICE CANDIDATE SENDING #$_iceCandidateSentCount via WS');
    print('[WebRTC] [$role] ICE counts: generated=$_iceCandidateGeneratedCount, sent=$_iceCandidateSentCount, received=$_iceCandidateReceivedCount');
    
    _sendSignaling({
      'type': 'ice_candidate',
      'payload': {
        'candidate': candidate.candidate,
        'sdpMid': candidate.sdpMid,
        'sdpMLineIndex': candidate.sdpMLineIndex,
      },
    });
  }
  
  /// Flush pending ICE candidates (call after WS is connected)
  void _flushPendingIceCandidates() {
    if (_pendingIceCandidates.isEmpty) return;
    
    final role = isHost ? 'HOST' : 'CONTROLLER';
    print('[WebRTC] [$role] Flushing ${_pendingIceCandidates.length} pending ICE candidates...');
    
    for (final candidate in _pendingIceCandidates) {
      _iceCandidateSentCount++;
      print('[WebRTC] [$role] ICE CANDIDATE SENDING (from queue) #$_iceCandidateSentCount');
      
      _sendSignaling({
        'type': 'ice_candidate',
        'payload': {
          'candidate': candidate.candidate,
          'sdpMid': candidate.sdpMid,
          'sdpMLineIndex': candidate.sdpMLineIndex,
        },
      });
    }
    
    _pendingIceCandidates.clear();
    print('[WebRTC] [$role] All pending ICE candidates flushed. Total sent: $_iceCandidateSentCount');
  }

  /// Track event (receive remote stream) - CONTROLLER receives video here
  void _onTrack(RTCTrackEvent event) {
    final role = isHost ? 'HOST' : 'CONTROLLER';
    print('[WebRTC] [$role] *** onTrack EVENT FIRED ***');
    print('[WebRTC] [$role] onTrack: track.kind=${event.track.kind}, track.id=${event.track.id}');
    print('[WebRTC] [$role] onTrack: track.enabled=${event.track.enabled}, track.muted=${event.track.muted}');
    print('[WebRTC] [$role] onTrack: streams count=${event.streams.length}');
    
    if (event.streams.isNotEmpty) {
      _remoteStream = event.streams[0];
      final videoTracks = _remoteStream!.getVideoTracks();
      final audioTracks = _remoteStream!.getAudioTracks();
      print('[WebRTC] [$role] Remote stream received:');
      print('[WebRTC] [$role]   stream.id=${_remoteStream!.id}');
      print('[WebRTC] [$role]   videoTracks=${videoTracks.length}, audioTracks=${audioTracks.length}');
      
      for (int i = 0; i < videoTracks.length; i++) {
        final vt = videoTracks[i];
        print('[WebRTC] [$role]   videoTrack[$i]: id=${vt.id}, enabled=${vt.enabled}, muted=${vt.muted}');
      }
      
      print('[WebRTC] [$role] Calling onRemoteStream callback...');
      onRemoteStream?.call(_remoteStream!);
      print('[WebRTC] [$role] onRemoteStream callback completed');
      
      // Schedule RTC stats logging after 5 seconds
      _scheduleStatsLogging();
    } else {
      print('[WebRTC] [$role] WARNING: onTrack fired but streams is EMPTY!');
    }
  }
  
  /// Log RTC stats after delay (for debugging video decode)
  void _scheduleStatsLogging() {
    Future.delayed(Duration(seconds: 5), () async {
      await _logRtcStats();
    });
  }
  
  /// Log RTC stats for debugging
  Future<void> _logRtcStats() async {
    if (_peerConnection == null) return;
    
    final role = isHost ? 'HOST' : 'CONTROLLER';
    print('[WebRTC] [$role] === RTC STATS (5s after track) ===');
    
    try {
      final stats = await _peerConnection!.getStats();
      for (final report in stats) {
        final type = report.type;
        final values = report.values;
        
        // Log inbound video stats (most important for controller)
        if (type == 'inbound-rtp' && values['kind'] == 'video') {
          print('[WebRTC] [$role] INBOUND VIDEO STATS:');
          print('[WebRTC] [$role]   bytesReceived: ${values['bytesReceived']}');
          print('[WebRTC] [$role]   packetsReceived: ${values['packetsReceived']}');
          print('[WebRTC] [$role]   framesDecoded: ${values['framesDecoded']}');
          print('[WebRTC] [$role]   framesDropped: ${values['framesDropped']}');
          print('[WebRTC] [$role]   frameWidth: ${values['frameWidth']}');
          print('[WebRTC] [$role]   frameHeight: ${values['frameHeight']}');
        }
        
        // Log outbound video stats (for host)
        if (type == 'outbound-rtp' && values['kind'] == 'video') {
          print('[WebRTC] [$role] OUTBOUND VIDEO STATS:');
          print('[WebRTC] [$role]   bytesSent: ${values['bytesSent']}');
          print('[WebRTC] [$role]   packetsSent: ${values['packetsSent']}');
          print('[WebRTC] [$role]   framesEncoded: ${values['framesEncoded']}');
        }
      }
    } catch (e) {
      print('[WebRTC] [$role] Stats error: $e');
    }
  }

  /// Report ICE state via WebSocket (NOT HTTP)
  void _reportIceStateViaWS(String iceState) {
    print('[WebRTC] Sending ICE state via WS: $iceState');
    _sendSignaling({
      'type': 'ice_state',
      'payload': {'state': iceState},
    });
  }
  
  /// Send signaling message
  void _sendSignaling(Map<String, dynamic> data) {
    final role = isHost ? 'HOST' : 'CONTROLLER';
    final msgType = data['type'] ?? 'unknown';
    
    if (_wsChannel == null) {
      print('[WebRTC] [$role] ERROR: _wsChannel is NULL when trying to send type=$msgType');
      return;
    }
    
    try {
      final jsonStr = json.encode(data);
      print('[WebRTC] [$role] >>> SENDING via WS: type=$msgType, size=${jsonStr.length} bytes');
      _wsChannel!.sink.add(jsonStr);
      print('[WebRTC] [$role] >>> SENT OK: type=$msgType');
    } catch (e) {
      print('[WebRTC] [$role] ERROR sending via WS: $e');
    }
  }

  /// Get remote stream for rendering
  MediaStream? get remoteStream => _remoteStream;

  /// Helper to force a specific codec (e.g. 'VP8') to be the preferred one in SDP
  String _preferCodec(String sdp, String codec) {
    print('[WebRTC] _preferCodec called for $codec');
    final lines = sdp.split('\r\n');
    final mLineIndex = lines.indexWhere((line) => line.startsWith('m=video'));
    if (mLineIndex == -1) {
      print('[WebRTC] WARNING: No m=video line found in SDP');
      return sdp;
    }

    // Parse the m-line to get payload types
    // m=video <port> <proto> <fmt1> <fmt2> ...
    final mLine = lines[mLineIndex];
    final parts = mLine.split(' ');
    if (parts.length < 4) return sdp;

    final fmtList = parts.sublist(3); // available payload types
    int? codecPayloadType;

    // Find the payload type for the desired codec
    for (final line in lines) {
      if (line.startsWith('a=rtpmap:')) {
        // a=rtpmap:<payloadType> <encodingName>/<clockRate>...
        final rtpmapParts = line.substring(9).split(' ');
        if (rtpmapParts.length >= 2) {
          final pt = int.tryParse(rtpmapParts[0]);
          final encoding = rtpmapParts[1].split('/')[0];
          if (encoding.toUpperCase() == codec.toUpperCase()) {
            codecPayloadType = pt;
            break;
          }
        }
      }
    }

    if (codecPayloadType == null) {
      print('[WebRTC] WARNING: Codec $codec not found in SDP');
      return sdp;
    }

    // Move preferred codec to the front of the fmt list
    final ptStr = codecPayloadType.toString();
    fmtList.remove(ptStr);
    fmtList.insert(0, ptStr);

    // Reconstruct m-line
    parts.replaceRange(3, parts.length, fmtList);
    lines[mLineIndex] = parts.join(' ');
    
    print('[WebRTC] SDP modified to prefer $codec (PT=$ptStr)');
    return lines.join('\r\n');
  }

  /// Disconnect and cleanup
  Future<void> disconnect() async {
    _wsChannel?.sink.close();
    await _localStream?.dispose();
    await _remoteStream?.dispose();
    await _peerConnection?.close();
    
    _wsChannel = null;
    _localStream = null;
    _remoteStream = null;
    _peerConnection = null;
    
    print('[WebRTC] Disconnected');
  }
}
